
// Query 1
PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city ?season WHERE { ?city onto:season ?season}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:season "Summer"}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:season "Winter"}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:season "Fall"}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:season "Spring"}

// Query 2

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city ?category WHERE { ?city onto:type ?category}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:type "Historic"}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:type "Entertainment"}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>"
SELECT ?city WHERE { ?city onto:type "Relaxation"}


// Query 3

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?city <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction.
?city rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#City>}


PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Hawaii> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}


PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Dubai> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Luxor> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#New_York> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Rome> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

// Query 4

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?ranking WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#rate> ?ranking} ORDER BY ?ranking

// Query 5

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#rate> ?ranking.
FILTER(?ranking = 3.0)}

// Query 6

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#openingHours> ?hours.
FILTER(contains(?hours, "am")).}

// Query 7

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#openingHours> ?hours.
FILTER(contains(?hours, "pm")).}

// Query 8

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?price  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#price> ?price.}

// Query 9

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?price  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Historical>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#price> ?price.}ORDER BY ?price

// Query 10

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
?city <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction.
?city rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#City>}


PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Hawaii> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}


PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Dubai> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Luxor> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#New_York> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?city WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Rome> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#has> ?attraction}

// Query 11

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction ?price  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Sports>.
?attraction onto:price ?price}

// Query 12

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?waterSport  WHERE {<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#sports_water_sports> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#recommends> ?waterSport.}

// Query 13

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?waterSport ?price  WHERE {<http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#sports_water_sports> <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#recommends> ?waterSport.
?waterSport onto:price ?price.
FILTER (?price < 1000)}

// Query 14

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?sport ?user ?sportType WHERE {?user rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#User>.
?user <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#interestedIn> ?sportType.
?sportType <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#recommends> ?sport.
filter(contains(str(?sportType), "sports")).}

// Query 15
PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?entertainment WHERE {?entertainment rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Entertainment>.}

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?entertainment ?user ?entertainmentType WHERE {?user rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#User>.
?user <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#interestedIn> ?entertainmentType.
?entertainmentType <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#recommends> ?entertainment.
filter(contains(str(?entertainmentType), "entertainment")).}

// Query 17

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Entertainment>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#openingHours> ?hours.
FILTER(contains(?hours, "am")).}

// Query 18

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Entertainment>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#openingHours> ?hours.
FILTER(contains(?hours, \"am\")).
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#price> ?price.
FILTER(?price < 100).}

// Query 19

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?attraction  WHERE {?attraction rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Entertainment>.
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#openingHours> ?hours.
FILTER(contains(?hours, \"am\")).
?attraction <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#duration> ?duration.
FILTER(?duration = 2).}

// Query 20

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?restaurant ?cuisine  WHERE {?restaurant rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Food>.
?restaurant onto:cuisine ?cuisine.}

// Query 21

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?restaurant  WHERE {?restaurant rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Food>.
?restaurant onto:cuisine ?cuisine.
FILTER(contains(?cuisine, "Seafood")).}

// Query 22

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?restaurant  WHERE {?restaurant rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Food>.
?restaurant onto:cuisine ?cuisine.
?restaurant onto:price ?price.
FILTER(?price <= 100).
FILTER(contains(?cuisine, \"American\"))}

// Query 23

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?restaurant ?rate  WHERE {?restaurant rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Food>.
?restaurant onto:rate ?rate.}

// Query 24

PREFIX onto: <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?restaurant ?rate  WHERE {?restaurant rdf:type <http://www.semanticweb.org/mohamed/ontologies/2017/2/TouristOnto#Food>.
?restaurant onto:cuisine ?cuisine.
?restaurant onto:rate ?rate.
FILTER(contains(?cuisine, \"Seafood\")).}











